######################################################################################################
#   ▄▄       ▄▄   ▄▄▄▄▄▄▄▄▄▄▄   ▄▄        ▄   ▄         ▄   ▄         ▄   ▄▄        ▄   ▄▄▄▄▄▄▄▄▄▄▄  #
#  ▐░░▌     ▐░░▌ ▐░░░░░░░░░░░▌ ▐░░▌      ▐░▌ ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░░▌      ▐░▌ ▐░░░░░░░░░░░▌ #
#  ▐░▌░▌   ▐░▐░▌ ▐░█▀▀▀▀▀▀▀█░▌ ▐░▌░▌     ▐░▌ ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌░▌     ▐░▌  ▀▀▀▀█░█▀▀▀▀  #
#  ▐░▌▐░▌ ▐░▌▐░▌ ▐░▌       ▐░▌ ▐░▌▐░▌    ▐░▌ ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌▐░▌    ▐░▌      ▐░▌      #
#  ▐░▌ ▐░▐░▌ ▐░▌ ▐░█▄▄▄▄▄▄▄█░▌ ▐░▌ ▐░▌   ▐░▌ ▐░█▄▄▄▄▄▄▄█░▌ ▐░▌       ▐░▌ ▐░▌ ▐░▌   ▐░▌      ▐░▌      #
#  ▐░▌  ▐░▌  ▐░▌ ▐░░░░░░░░░░░▌ ▐░▌  ▐░▌  ▐░▌ ▐░░░░░░░░░░░▌ ▐░▌       ▐░▌ ▐░▌  ▐░▌  ▐░▌      ▐░▌      #
#  ▐░▌   ▀   ▐░▌ ▐░█▀▀▀▀▀▀▀█░▌ ▐░▌   ▐░▌ ▐░▌ ▐░█▀▀▀▀▀▀▀█░▌ ▐░▌       ▐░▌ ▐░▌   ▐░▌ ▐░▌      ▐░▌      #
#  ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌    ▐░▌▐░▌ ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌    ▐░▌▐░▌      ▐░▌      #
#  ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌     ▐░▐░▌ ▐░▌       ▐░▌ ▐░█▄▄▄▄▄▄▄█░▌ ▐░▌     ▐░▐░▌      ▐░▌      #
#  ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌      ▐░░▌ ▐░▌       ▐░▌ ▐░░░░░░░░░░░▌ ▐░▌      ▐░░▌      ▐░▌      #
#   ▀         ▀   ▀         ▀   ▀        ▀▀   ▀         ▀   ▀▀▀▀▀▀▀▀▀▀▀   ▀        ▀▀        ▀       #
######################################################################################################
#                               Minecraft Manhunt by Radialbog9                                      #
######################################################################################################

### Settings ###
# These are the default settings, most of which can be changed in the new settings menu

# Gives runner(s) a head start by giving hunter(s) blindness, slowness, and weakness
# Set to false for a more authentic manhunt.
head-start:
  # Head start enabled?
  enabled: true
  # Length of the head start (in seconds)
  length: 30

# Sends a welcome message to those who have manhunt permissions on join
# Currently doesn't do anything
join-message: true
join-message-noperm: '&aWelcome to this Manhunt server!'
join-message-perm: '&aWelcome! Use /manhunt runner and /manhunt hunter to add players and /manhunt settings to change settings and start the game!'

# Kits feature
# Currently doesn't do anything
kits:
  runners:
    default:
  hunters:
    default:
      - COMPASS

### Language ###
# Some entries have required arguments (such as player names) which are indicated by '%s'.
# The arguments have to be in the order they were set in the default language.
language:
  # General language
  no-permission: '&6[Manhunt]&r&a You do not have permission to do this!'
  player-not-online: '&6[Manhunt]&r&a The player&r&c %s &r&ais not online!'
  unknown-subcommand: '&6[Manhunt]&r&a Unknown subcommand!'
  not-enough-args: '&6[Manhunt]&r&a Not enough arguments!'
  too-many-args: '&6[Manhunt]&r&a Too many arguments!'
  no-game-in-progress: '&6[Manhunt]&r&a There is no game in progress.'
  join-in-progress: '&6[Manhunt]&r&a A game is in progress so you have been put into spectator!'
  # Main command
  no-command-specified: '&6[Manhunt]&r&a No command specified. Type /manhunt help for command help.'
  # Help and usage
  no-subcommand-perm: '&a- You do not have permission for any sub-commands.'
  usage: '&6[Manhunt]&r&a Usage:&c %s'
  # Hunters
  now-hunter: '&6[Manhunt]&r&a You are now a hunter!'
  no-change-hunter-in-game: '&6[Manhunt]&r&a You can not change hunters while the game is ongoing.'
  hunter-disconnected: '&6[Manhunt]&r&c %s &r&ahas disconnected. They are no longer a hunter.'
  # Hunter compass
  tracking-player: '&6[Manhunt]&r&a Tracking player&r&c %s&r&a.'
  no-players-to-track: '&6[Manhunt]&r&a &cNo players found to track.'
  # Runners
  now-runner: '&6[Manhunt]&r&a You are now a runner!'
  no-change-runner-in-game: '&6[Manhunt]&r&a You can not change runners while the game is ongoing.'
  runner-died: '&6[Manhunt]&r&c %s &r&adied. There are now&r&c %s &r&aremaining.'
  runner-disconnected: '&6[Manhunt]&r&c %s &r&ahas disconnected. They are no longer a runner.'
  # Remove players
  no-remove-in-game: '&6[Manhunt]&r&a You can not remove players while the game is ongoing.'
  now-spectator: '&6[Manhunt]&r&a You are now a spectator!'
  # Start and stop game
  game-started: '&6[Manhunt]&r&a The game has started!'
  too-few-players: '&6[Manhunt]&r&a The game must have at least 1 hunter and 1 runner!'
  game-already-in-progress: '&6[Manhunt]&r&a A game is already in progress!'
  game-ended: '&6[Manhunt]&r&a The game has ended!'
  game-ended-prematurely: '&6[Manhunt]&r&a The game has been stopped!'
  # Game end causes
  no-more-runners-left: '&6[Manhunt]&r&a There are no more runners on the server! Hunters win!'
  all-runners-dead: '&6[Manhunt]&r&a There are no more runners left alive! Hunters win!'
  no-more-hunters-left: '&6[Manhunt]&r&a There are no more hunters on the server! Runners win!'
  runners-kill-ender-dragon: '&6[Manhunt]&r&a The runners have killed the Ender Dragon! Runners Win!'
  time-up: '&6[Manhunt]&r&a The runner has not been killed in time! Hunters win!'
  # Manhunt player list
  game-is-started: '&6[Manhunt]&r&a The game is &r&cstarted&r&a.'
  game-is-stopped: '&6[Manhunt]&r&a The game is &r&cstopped&r&a.'
  list-count: '&6[Manhunt]&r&a There are&r&c %s &r&ahunters,&r&c %s &r&arunners, and&r&c %s &r&aspectators.'
  hunter-list: '&6[Manhunt]&r&a Hunters: %s'
  runner-list: '&6[Manhunt]&r&a Runners: %s'
  spectator-list: '&6[Manhunt]&r&a Spectators: %s'
  # - The two variables below at default values would give something like "&r&cNotch&r&a, &r&cjeb_&r&a" in the manhunt player list
  list-name-prefix: '&r&c'
  list-name-suffix: '&r&a'
  # Spectate command
  console-cannot-spectate: '&6[Manhunt]&r&a Console cannot spectate players!'
  not-spectator: '&6[Manhunt]&r&a You are not a spectator!'
  now-spectating-player: '&6[Manhunt]&r&a You are now spectating&c %s&r&a.'
  # Settings menu (doesn't do anything yet)
  settingsmenu:
    title: '&7---- &6Manhunt Settings Menu &7----'
    enabled: '&a✓'
    disabled: '&c✕'
    click-to-toggle: '&6Click to toggle!'
    click-to-change: '&6Click to change!'
    click-to-start: '&6Click to start!'
    options:
      head-start: '&7[ &r%s &r&7] &eHead start'
      head-start-timer: '&7[ &r&a%s seconds &r&7] &eHead start timer'
      start-game: '&eStart game'