######################################################################################################
#   ▄▄       ▄▄   ▄▄▄▄▄▄▄▄▄▄▄   ▄▄        ▄   ▄         ▄   ▄         ▄   ▄▄        ▄   ▄▄▄▄▄▄▄▄▄▄▄  #
#  ▐░░▌     ▐░░▌ ▐░░░░░░░░░░░▌ ▐░░▌      ▐░▌ ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░░▌      ▐░▌ ▐░░░░░░░░░░░▌ #
#  ▐░▌░▌   ▐░▐░▌ ▐░█▀▀▀▀▀▀▀█░▌ ▐░▌░▌     ▐░▌ ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌░▌     ▐░▌  ▀▀▀▀█░█▀▀▀▀  #
#  ▐░▌▐░▌ ▐░▌▐░▌ ▐░▌       ▐░▌ ▐░▌▐░▌    ▐░▌ ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌▐░▌    ▐░▌      ▐░▌      #
#  ▐░▌ ▐░▐░▌ ▐░▌ ▐░█▄▄▄▄▄▄▄█░▌ ▐░▌ ▐░▌   ▐░▌ ▐░█▄▄▄▄▄▄▄█░▌ ▐░▌       ▐░▌ ▐░▌ ▐░▌   ▐░▌      ▐░▌      #
#  ▐░▌  ▐░▌  ▐░▌ ▐░░░░░░░░░░░▌ ▐░▌  ▐░▌  ▐░▌ ▐░░░░░░░░░░░▌ ▐░▌       ▐░▌ ▐░▌  ▐░▌  ▐░▌      ▐░▌      #
#  ▐░▌   ▀   ▐░▌ ▐░█▀▀▀▀▀▀▀█░▌ ▐░▌   ▐░▌ ▐░▌ ▐░█▀▀▀▀▀▀▀█░▌ ▐░▌       ▐░▌ ▐░▌   ▐░▌ ▐░▌      ▐░▌      #
#  ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌    ▐░▌▐░▌ ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌    ▐░▌▐░▌      ▐░▌      #
#  ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌     ▐░▐░▌ ▐░▌       ▐░▌ ▐░█▄▄▄▄▄▄▄█░▌ ▐░▌     ▐░▐░▌      ▐░▌      #
#  ▐░▌       ▐░▌ ▐░▌       ▐░▌ ▐░▌      ▐░░▌ ▐░▌       ▐░▌ ▐░░░░░░░░░░░▌ ▐░▌      ▐░░▌      ▐░▌      #
#   ▀         ▀   ▀         ▀   ▀        ▀▀   ▀         ▀   ▀▀▀▀▀▀▀▀▀▀▀   ▀        ▀▀        ▀       #
######################################################################################################
#                               Minecraft Manhunt by Radialbog9                                      #
######################################################################################################

#
# Copyright (c) 2021 Radialbog9/TheJoeCoder and contributors.
# You are allowed to use this code under the GPL3 license, which allows commercial use, distribution, modification, and licensed works, providing that you distribute your code under the same or similar license.
#

### Settings ###
# These are the default settings, most of which will be changable in the upcoming settings menu

# Gives runner(s) a head start by giving hunter(s) blindness, slowness, and weakness.
# Set to false in here or in the settings menu for a more authentic manhunt.
head-start:
  # Head start enabled?
  enabled: true
  # Length of the head start (in seconds)
  length: 30

# If set to true, the hunters will be able to damage the Ender Dragon.
# If set to false, all damage to the Ender Dragon from hunters will be cancelled.
allow-hunters-damage-dragon: false

# If set to true, the hunters will be able to destroy End Crystals.
# If set to false, hunters will not be able to damage or destroy End Crystals.
allow-hunters-damage-crystal: true

# Changes the time allowed for 'survive' objective games
survive-game-length: 600

### SCENARIOS ###
scenarios:
  RUNNER_CREATIVE:
    # Runners are set to creative every `time` seconds.
    time: 300
    # Runners can keep creative for `duration` seconds.
    duration: 5
    # ALlow flying while runners in creative?
    allow-fly: false
  HUNTER_CREATIVE:
    # Hunters are set to creative every `time` seconds.
    time: 300
    # Hunters can keep creative for `duration` seconds.
    duration: 5
    # ALlow flying while hunters in creative?
    allow-fly: false
  HUNTER_RANDOM_MOB_DISGUISE:
    # Hunters are disguised as mobs every `time` seconds
    time: 300
  RUNNER_RANDOM_MOB_DISGUISE:
    # Runners are disguised as mobs every `time` seconds
    time: 300
  RUNNER_RANDOM_HUNTER_DISGUISE:
    # Runners are disguised as hunters every `time` seconds
    time: 300
  RANDOM_LUCKY_DROPS:
    # Players get lucky drops every `time` seconds
    time: 300
  RANDOM_PROJECTILES:
    # Players get random projectiles every `time` seconds
    time: 300
  HUNTER_RANDOM_MOBS:
    # Random mobs spawn at hunters every `time` seconds
    time: 180
  POISONOUS_AIR:
    # Players get poisoned every `time` seconds
    # Should be set to 1
    time: 1
  SNEAK_DISABLES:
    # Players can't sneak every `time` seconds
    time: 300
    # Players can't sneak for `duration` seconds
    duration: 5
  HUNTER_RANDOM_POTION_EFFECT:
    # Hunters get random potion effects every `time` seconds
    time: 300
    # Hunters get random potion effects for `duration` seconds
    duration: 5
    # Amplifier of the potion effect
    amplifier: 1
  RUNNER_RANDOM_POTION_EFFECT:
    # Runners get random potion effects every `time` seconds
    time: 300
    # Runners get random potion effects for `duration` seconds
    duration: 5
    # Amplifier of the potion effect
    amplifier: 1
  RUNNER_INVISIBILITY:
    # Runners get random potion effects every `time` seconds
    time: 300
    # Runners get random potion effects for `duration` seconds
    duration: 5
    # Amplifier of the potion effect
    amplifier: 1
  RUNNER_GHOSTS:
    # Runners become ghosts every `time` seconds
    time: 400
    # Runners become ghosts for `duration` seconds
    duration: 10

### Join Message ###
join-message:
  enabled: true
  noperm: '&aWelcome to this Manhunt server! The game will start shortly.'
  perm: '&aWelcome! Use /manhunt runner and /manhunt hunter to add players and /manhunt settings to change settings and start the game!'

### Language preferences ###
# Set this to one of the supported languages.
# Set this to 'custom' to generate a custom language file.
language: 'en_GB'