name: Manhunt
main: uk.radialbog9.spigot.manhunt.Manhunt
version: ${project.version}
description: Play Dream's iconic Manhunt game!
author: Radialbog9
api-version: '1.17'
softdepend:
  - SuperVanish
  - PremiumVanish
  - LibsDisguises
  - ProtocolLib
permissions:
  manhunt.*:
    description: Allows player to use all manhunt commands
    children:
      manhunt.add: true
      manhunt.remove: true
      manhunt.start: true
      manhunt.stop: true
      manhunt.list: true
      manhunt.spectate: true
      manhunt.admin: true
      manhunt.settings: true
      manhunt.scenarios: true
      manhunt.revive: true
      manhunt.updates: true
  manhunt.add:
    description: 'Allows player to add others to hunters/runners'
    default: 'op'
  manhunt.remove:
    description: 'Allows player to remove others from the game'
    default: 'op'
  manhunt.start:
    description: 'Allows player to start the game'
    default: 'op'
  manhunt.stop:
    description: 'Allows player to stop the game'
    default: 'op'
  manhunt.list:
    description: 'Allows player to list other players in the game'
    default: 'true'
  manhunt.settings:
    description: 'Allows player to change settings in the game'
    default: 'op'
  manhunt.scenarios:
    description: 'Allows player to change scenarios in the game'
    default: 'op'
  manhunt.spectate:
    description: 'Allows player to spectate hunters/runner while in a game'
    default: 'true'
  manhunt.admin:
    description: 'Sends join messages for admins on joining (if enabled)'
    default: 'op'
  manhunt.revive:
    description: 'Allows player to revive dead hunters'
    default: 'op'
  manhunt.updates:
    description: 'Allows player to receive new update messages'
    default: 'op'